"""Add extensive ProjectCategory enum and fix status types.

Revision ID: 02472df4f2f0
Revises: 9b9c3fe22cba
Create Date: 2025-11-18 21:45:26.646606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02472df4f2f0'
down_revision: Union[str, Sequence[str], None] = '9b9c3fe22cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
