"""Add is_active to users

Revision ID: 4c73754f819b
Revises: ba2d5efea96c
Create Date: 2025-11-24 11:56:52.793233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c73754f819b'
down_revision: Union[str, Sequence[str], None] = 'ba2d5efea96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # 2. Mevcut tüm kullanıcıları varsayılan olarak 'True' (Aktif) yap
    op.execute("UPDATE users SET is_active = true")
    
    # 3. Artık hepsi dolu olduğu için sütunu 'nullable=False' (boş olamaz) kuralına çevir
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
