"""add_project_revisions_table

Revision ID: 9b9c3fe22cba
Revises: 1381f688079d
Create Date: 2025-11-18 14:30:13.428622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9c3fe22cba'
down_revision: Union[str, Sequence[str], None] = '1381f688079d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'budget_min',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('projects', 'budget_max',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('projects', 'budget_max',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('projects', 'budget_min',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('projects', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('project_revisions')
    # ### end Alembic commands ###
