"""Add project delivery notification types

Revision ID: c8e0cd7909c0
Revises: eee3cd5108c9
Create Date: 2025-08-12 16:27:51.749381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e0cd7909c0'
down_revision: Union[str, Sequence[str], None] = 'eee3cd5108c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Otomatik oluşturulan kod yerine, ENUM'a yeni değerleri eklemek için
    # doğrudan SQL komutları çalıştırıyoruz.
    op.execute("ALTER TYPE notification_type_enum ADD VALUE 'PROJECT_DELIVERED'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE 'DELIVERY_ACCEPTED'")
    op.execute("ALTER TYPE notification_type_enum ADD VALUE 'REVISION_REQUESTED'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # NOT: PostgreSQL'de bir ENUM değerini silmek karmaşık bir işlemdir
    # ve eğer o değer veritabanında kullanılıyorsa hataya neden olur.
    # Bu yüzden genellikle downgrade işlemi boş bırakılır veya manuel yapılır.
    # Şimdilik bu şekilde bırakmamız en güvenlisi.
    pass
    
    # ### end Alembic commands ###