"""Add notification and push token fields to users

Revision ID: e36be93cc08e
Revises: 6fea26e1a263
Create Date: 2026-04-21 16:25:45.010403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36be93cc08e'
down_revision: Union[str, Sequence[str], None] = '6fea26e1a263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expo_push_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('push_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('marketing_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_enabled')
    op.drop_column('users', 'email_enabled')
    op.drop_column('users', 'push_enabled')
    op.drop_column('users', 'expo_push_token')
    # ### end Alembic commands ###
