# samconfig.toml
version = 0.1

[default.deploy.parameters]
stack_name = "tasarimcibulutu"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qqp3uh8ecuzy"
s3_prefix = "tasarimcibulutu"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
region = "eu-north-1" # Global parametreyi buraya taşıdım

parameter_overrides = [
  "S3BucketName=\"tasarimcibulutu-showcase-files-ahmet\"",
  "VpcId=\"vpc-042d4881f4efd3d20\"",
  "SubnetIds=\"subnet-0f01188cd159af66f\"",
  "SecurityGroupIds=\"sg-0b64a1f400813e7c6\"",
  "MailFrom=\"ahmetberkekaya04@gmail.com\"",
  "MailPort=587",
  "MailServer=\"smtp.sendgrid.net\"",
]

[default.global.parameters]


